### ISSUE TITLE
No exit code on errors?

### ISSUE THREAD

**Issue by albrektsson** [nais/salsa#167]
Slsa doesn't throw an exit code if something in the workflow fails? Expected exit code > 0 ?

```
---------- Preparing pico-de-galo SLSA ----------
---------- Logging in to Docker registry: *** ----------
Error response from daemon: Get "https://***/v2/": dial tcp: lookup ***: Temporary failure in name resolution
---------- Clean up Google Cloud stuff ----------
```

Example workflow run: https://github.com/navikt/omsorgsdager/actions/runs/4362091341/jobs/7626603426

**Comment by tommytroen** [comment]
This repo will be archived so closing this issue.
