### ISSUE TITLE
Split verify into its own subcommand of verify

### ISSUE THREAD

**Issue by anderssonw** [nais/salsa#186]
**Is your feature request related to a problem? Please describe.**
attest-verify is janky, as it is not really a part of the attest command, but rather a flag/subcommand

**Describe the solution you'd like**
verify should be its own subcommand under attest, with its own flags and defaults. a few of the flags will be duplicated, so should probably move these to some utility

**Comment by tommytroen** [comment]
This repo will be archived so closing this issue.
