### ISSUE TITLE
create credentialhelper for docker login in entrypoint

### ISSUE THREAD

**Issue by tommytroen** [nais/salsa#20]
ref:

Configure a credential helper to remove this warning. See
https://docs.docker.com/engine/reference/commandline/login/#credentials-store

**Comment by ybelMekk** [comment]
https://github.com/stuartsierra/password-store

**Comment by ybelMekk** [comment]
docker logout $DOCKER_REGISTRY deletes the secret, docker-login action uses same strategy.
