### ISSUE TITLE
bug: missing digests for some dependencies

### ISSUE THREAD

**Issue by tommytroen** [nais/salsa#21]
See provenance for http://github.com/nais/onion:

`
uri | "pkg:io.ktor:ktor-http:1.5.3"
-- | --
digest |  
  | ""
10 |  
uri | "pkg:io.ktor:ktor-utils:1.5.3"
digest |  
  | ""
11 |  
uri | "pkg:io.ktor:ktor-io:1.5.3"
digest |  
  |  
`

**Comment by ybelMekk** [comment]
fixed by: https://github.com/nais/salsa/commit/dd25ca65693e7b21dd15ec04dbf9363ede201c9c
